// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "fs";
import path from "path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// .env na pasta server (cwd ao rodar do server, ou cwd/server ao rodar da raiz)
const cwd = process.cwd();
const envPath = fs.existsSync(path.join(cwd, "server", ".env"))
  ? path.join(cwd, "server", ".env")
  : path.join(cwd, ".env");
dotenv.config({ path: envPath, override: true });

let url: string | undefined = process.env.DATABASE_URL;
if (!url?.startsWith("mysql://")) {
  const content = fs.readFileSync(envPath, "utf-8");
  const m = content.match(/mysql:\/\/[^\s"'\r\n#]+/);
  url = m ? m[0].trim() : undefined;
}
if (!url?.startsWith("mysql://"))
  throw new Error(
    `DATABASE_URL deve ser MySQL. Em ${envPath} use: DATABASE_URL="mysql://usuario:senha@localhost:3306/nome_do_banco"`
  );

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
