/**
 * Lista centralizada de códigos de permissão.
 * Ao adicionar novas permissões, inclua aqui. Depois execute:
 *   npm run prisma:sync-permissions --prefix server
 */
export const PERMISSION_CODES = [
  // Administrativo
  'ADMINISTRATIVO.USUARIO.LISTAR',
  'ADMINISTRATIVO.USUARIO.CRIAR',
  'ADMINISTRATIVO.USUARIO.EDITAR',
  'ADMINISTRATIVO.USUARIO.EXCLUIR',
  'ADMINISTRATIVO.CARGO.LISTAR',
  'ADMINISTRATIVO.CARGO.CRIAR',
  'ADMINISTRATIVO.CARGO.EDITAR',
  'ADMINISTRATIVO.CARGO.EXCLUIR',
  // Configuração
  'CONFIGURACAO.APARELHO.LISTAR',
  'CONFIGURACAO.APARELHO.CRIAR',
  'CONFIGURACAO.APARELHO.EDITAR',
  'CONFIGURACAO.APARELHO.EXCLUIR',
  // Agendamento & Ordens
  'AGENDAMENTO.CLIENTE.LISTAR',
  'AGENDAMENTO.CLIENTE.CRIAR',
  'AGENDAMENTO.CLIENTE.EDITAR',
  'AGENDAMENTO.CLIENTE.EXCLUIR',
  'AGENDAMENTO.TECNICO.LISTAR',
  'AGENDAMENTO.TECNICO.CRIAR',
  'AGENDAMENTO.TECNICO.EDITAR',
  'AGENDAMENTO.TECNICO.EXCLUIR',
  'AGENDAMENTO.OS.LISTAR',
  'AGENDAMENTO.OS.CRIAR',
  'AGENDAMENTO.OS.EDITAR',
  'AGENDAMENTO.OS.EXCLUIR',
  'AGENDAMENTO.PEDIDO_RASTREADOR.LISTAR',
  'AGENDAMENTO.PEDIDO_RASTREADOR.CRIAR',
  'AGENDAMENTO.PEDIDO_RASTREADOR.EDITAR',
  'AGENDAMENTO.PEDIDO_RASTREADOR.EXCLUIR',
] as const
