export const ROLES_CONTROLLER_PERMISSIONS = {
  CARGO_LISTAR: 'ADMINISTRATIVO.CARGO.LISTAR',
  CARGO_CRIAR: 'ADMINISTRATIVO.CARGO.CRIAR',
  CARGO_EDITAR: 'ADMINISTRATIVO.CARGO.EDITAR',
  USUARIO_LISTAR: 'ADMINISTRATIVO.USUARIO.LISTAR',
  USUARIO_EDITAR: 'ADMINISTRATIVO.USUARIO.EDITAR',
} as const;
