import type { OrdemCadastro, OSResponse } from "@/types/cadastro-rastreamento";

export const osRespostaBase: OSResponse = {
  id: 42,
  tipo: "REVISAO",
  statusCadastro: "AGUARDANDO",
  idAparelho: "IMEI-ENT",
  iccidAparelho: "89012",
  idEntrada: null,
  iccidEntrada: null,
  plataforma: null,
  concluidoEm: null,
  localInstalacao: "Porta A",
  posChave: "Sim",
  localInstalacaoEntrada: null,
  posChaveEntrada: null,
  criadoEm: "2024-06-10T12:00:00.000Z",
  cliente: { nome: "Cliente X" },
  subcliente: { nome: "Sub Y" },
  tecnico: { nome: "Técnico Z" },
  veiculo: {
    placa: "ABC1D23",
    marca: "Fiat",
    modelo: "Uno",
    cor: "Prata",
    ano: 2020,
  },
  concluidoPor: null,
  aparelhoEntrada: {
    marca: "Tel",
    modelo: "T100",
    iccid: "111",
    sim: { operadora: "Vivo", marcaNome: "M2M", planoMb: 5 },
  },
  aparelhoSaida: {
    marca: "Tel",
    modelo: "T200",
    iccid: "222",
    sim: null,
  },
};

export const ordemMinima: OrdemCadastro = {
  id: 1,
  status: "AGUARDANDO",
  tipoRegistro: "CADASTRO",
  instalacaoComBloqueio: true,
  cliente: "C",
  subcliente: null,
  tipoServico: "Inst",
  tecnico: "T",
  veiculo: "V",
  placa: "P",
  cor: "c",
  modelo: "m",
  modeloAparelhoEntrada: "mod",
  imei: "i",
  iccid: "ic",
  local: "l",
  posChave: "pk",
  imeiSaida: null,
  iccidSaida: null,
  modeloSaida: null,
  data: "d",
  plataforma: null,
  concluidoEm: null,
  concluidoPor: null,
};
